AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description:  bowl_picker_backend

Parameters:
  ZipBucket:
    Type: String
    Default: jtcruthers-lambda-zipfiles

Resources:

  GetBowlPicks:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetBowlPicks
      Handler: get_picks.lambda_handler
      Role: !GetAtt GetBowlPicksRole.Arn
      Runtime: python3.8
      Code:
        S3Bucket: !Ref ZipBucket
        S3Key: get_picks.zip

  GetBowlPicksRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: GetBowlPickPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Scan
            Resource: arn:aws:dynamodb:us-east-2:291992694103:table/bowl-picks

  SaveBowlPicks:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SaveBowlPicks
      Handler: save_picks.lambda_handler
      Role: !GetAtt SaveBowlPicksRole.Arn
      Runtime: python3.8
      Code:
        S3Bucket: !Ref ZipBucket
        S3Key: get_picks.zip

  SaveBowlPicksRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: GetBowlPickPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            Resource: arn:aws:dynamodb:us-east-2:291992694103:table/bowl-picks

  BowlPicksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bowl-picks
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  BowlPicksRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "bowl-picker-api"
      Description: "Bowl Picker API"

  GetPicksApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: get_picks
      ParentId: !GetAtt BowlPicksRestApi.RootResourceId
      RestApiId: !Ref BowlPicksRestApi

  GetPicksApiMethod:
    Type: AWS::ApiGateway::Method
    Properties: 
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt GetBowlPicks.Arn
      ResourceId: !Ref GetPicksApiResource
      RestApiId: !Ref BowlPicksRestApi

  SavePicksApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: save_picks
      ParentId: !GetAtt BowlPicksRestApi.RootResourceId
      RestApiId: !Ref BowlPicksRestApi

  SavePicksApiMethod:
    Type: AWS::ApiGateway::Method
    Properties: 
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt SaveBowlPicks.Arn
      ResourceId: !Ref SavePicksApiResource
      RestApiId: !Ref BowlPicksRestApi

  BowlPicksBetaStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: "beta"
      DeploymentId: !Ref BowlPicksDeployment
      RestApiId: !Ref BowlPicksRestApi

  BowlPicksDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref BowlPicksRestApi
      StageName: "beta"
    DependsOn:
      - GetPicksApiMethod
      - SavePicksApiMethod